### ISSUE TITLE
[Feature Request] Patch target multiple paths

### ISSUE THREAD

**Issue by SettingDust** [EnderTurret/PatchedMod#12]
When I'm clear structures in the structure set. All the patch are exactly same. But I have to copy them again and again. That's painful.
I think a prop or a manifest of a patch is useful.

**Comment by EnderTurret** [comment]
(Side note: this issue affects only the mod, since the library has no knowledge of where the files and patches are coming from.)

I've noticed that there are circumstances where one wants a patch to apply to multiple targets (I know because I've wanted to do that before). The main problem with implementing this is I need to decide *how* I want to implement it. I expect I'm going to need to think on this for a while, since I need to come up with a way to allow the same patch to target multiple files *without* hurting discoverability (as right now, you can tell what file a patch patches based purely on the patch's filename, but adding multiple targets breaks that guarantee).

**Comment by SettingDust** [comment]
How about `mcmeta` file for `.json.patch`? For discoverability, a `mcmeta` file will be notable for viewers to know it's a special patch instead of the normal one

**Comment by EnderTurret** [comment]
This has now been implemented as of version `5.1.0+1.20.4`.
