### ISSUE TITLE
Cavernous New Version

### ISSUE THREAD

**Issue by Boba194230** [EnderTurret/PatchedMod#13]
So I've made patches for the new version of cavernous and they seem to sorta work just not really as the biomes show up in the world when I locate them but they are very splotchy and not done correctly. I'm wondering if maybe I messed up when making the patches as if I take all of the patched stuff out and add the same code to my manual file it works fine. Heres the patches
 
[overworld.json.patch](https://github.com/EnderTurret/PatchedMod/files/13405188/overworld.json.patch) from dimension folder
[overworld.json.patch](https://github.com/EnderTurret/PatchedMod/files/13405191/overworld.json.patch) from noise_settings
also as I said I don't really care about the vanilla biome changes too much as terralith handles that nicely so I deleted the biomes folder from the world gen and it still worked fine in my manual version.

**Comment by EnderTurret** [comment]
If you look in the log, are there any errors related to the patches?
I ask because from my cursory examination I noticed a json syntax error in the `noise_settings/overworld.json.patch` (a missing comma after the `path` line), which could be causing the problem you described (by causing the patch to not be applied). Otherwise, if that's not it (and there are no errors in the log), I can try and do a more detailed analysis later.

**Comment by Boba194230** [comment]
trying that rn, I guess I didn't catch it in VS Code since I didn't have the diff set to json to check

**Comment by Boba194230** [comment]
bruh

**Comment by Boba194230** [comment]
it works now, thank you so much XD. Can't believe it was just that *facepalm* I'll make sure to set that diff next time
