### ISSUE TITLE
(1.20.4) Firehose of mixin exceptions on server start

### ISSUE THREAD

**Issue by HatTrkPatrk** [EnderTurret/PatchedMod#15]
I'm running Fabric 1.20.4, Loader 0.15.7, API 0.96.11, and Patched 4.0.1. No other mods or even datapacks are installed yet.

Within seconds of attempting to start the server, the log is flooded with thousands of mixin exceptions. After just over 10 seconds of execution time, so many occurred that the log file ballooned to 750kb. I had to Ctrl+C the process to stop it from getting any worse.

https://gist.github.com/HatTrkPatrk/3411d1e21ed1c271c5300fd632c28e51

**Comment by HatTrkPatrk** [comment]
Followup, maybe this will help:

I went back and tried an older version of the Fabric API from around Dec 16 2023 (when Patched 4.0.1 was uploaded to modrinth) and it actually worked. So I incrementally tried upgrading the Fabric API to newer versions until the errors started happening again, which began with Fabric API version 0.95.4. The version before that (which worked) was 0.95.1.

**Comment by Boba194230** [comment]
Bump on this issue as well, thanks for letting me know 95.1 worked as that let me tell my users for now to revert to that version.

**Comment by EnderTurret** [comment]
It looks like the exact change that has caused Patched to break is [this one](https://github.com/FabricMC/fabric/commit/707e4d1bfda6a84d31c43c362fe09a0e1c78a264), which made all sorts of exciting changes to Fabric's resource/data pack internals. It seems like Patched has therefore been broken on Fabric 1.20.4+ since mid-January, which is not exactly ideal -- I'm just wondering why it took two whole months for it to come up. (Maybe 1.20.4 is an unpopular version?)

Regardless, I've been working on a new release which will include support for targeting multiple files with one patch (and for including the contents of patches inside other patches). That'll now also include a fix for this (and possibly any breaking changes on the NeoForge side of things). I'll also attempt to cut down on the logspam so that if this ever happens again it won't shred everyones' hard drives. Said release should exist sometime in the next few days, assuming I manage to find time to work on it. In the meantime, I guess the best option is to rollback to the last version of Fabric API that doesn't include this change (which does look to be `0.95.1`).

**Comment by Boba194230** [comment]
Awesome thanks, no rush. Yeah I’m still on 1.20.1 and don’t really plan on upgrading soon as a few of my “crucial” mods are still only 1.20.1

**Comment by EnderTurret** [comment]
It took significantly longer than I would have liked, but I've released version `5.1.0+1.20.4` which fixes the Fabric API compatibility errors. (It may take some time for the files to be reviewed.)
