### ISSUE TITLE
Upload 1.18.2 to CF for modpack use

### ISSUE THREAD

**Issue by SettingDust** [EnderTurret/PatchedMod#8]

**Comment by EnderTurret** [comment]
So the reason the 1.18.2 build on Modrinth wasn't *also* on CurseForge is because it was kind of old and had all kinds of bugs, like patches from mods just not applying at all. (Also, the CurseForge project was created after the Modrinth one, in the 1.19 era.)

Instead of putting that absolutely cursed build on CurseForge, I've gone and backported the 1.19.2 branch to 1.18.2, and that's now on CurseForge under review (and also theoretically available on Modrinth).

**Comment by SettingDust** [comment]
Thanks :D
